---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

#steps:
    ##  - name: greeting
  ##    commands:
  ##      - echo hello world

steps:
#  - name: build
#    commands:
#      - docker build -t springboot-helloworld:latest .

  - name: deploy
    when:
      branch:
        - main
    commands:
      - mkdir /root/workspace